# Generated by Django 5.1 on 2024-08-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='MRP',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=11),
        ),
    ]
